call SETUSSSMSTEMPLATEKEY('rp.apiType.96.spss.success', 'Доступная Вам сумма Доверит. платежа: {.case {.compare {CUR}}{.when R}{.then{.case{.compare{sumOutsideRoaming1}}{.when 0.00}{.then }{.else{sumOutsideRoaming1}руб.}}{.case{.compare{sumInRoaming1}} {.when 0.00}{.then }{.else в роуминге: {sumInRoaming1 } руб.}}{.case{.compare{sumOutsideRoaming1}}{.when 0.00}{.then }{.else Стоимость подключения {costOutsideRoaming1} руб.}}}{.else{.case{.compare{sumOutsideRoaming1}}{.when 0.00}{.then }{.else ${sumOutsideRoaming1}}}{.case{.compare{sumInRoaming1}}{.when 0.00}{.then }{.else в роуминге: ${sumInRoaming1} руб.}}{.case{.compare{sumOutsideRoaming1}}{.when 0.00}{.then}{.else Стоимость подключения ${costOutsideRoaming1} }}}}', 'ru_RU');
call SETUSSSMSTEMPLATEKEY('rp.apiType.96.spss.new.success', 'Уважаемый абонент, у Вас есть непогашенный Доверительный платеж. Напоминаем, что предыдущий Доверительный платеж {.case {.compare {CUR}}{.when R}{.then {PRPVAL} р за {PRPVALR} р спишется {PRPDAYS}. Также Вам доступна дополнительная сумма Доверительного платежа  {TP2SUM} р. Общая сумма к оплате составит {ALLCOST} рублей за {ALLFEE} рублей.}{.else {PRPVAL}$ за {PRPVALR}$ спишется {PRPDAYS}. Также Вам доступна дополнительная сумма Доверительного платежа  {TP2SUM} $. Общая сумма к оплате составит {ALLCOST}$ за {ALLFEE}$.}} Вы можете пополнить баланс быстро и без комиссии через приложение "Мой Билайн" www.beeline.ru/dl', 'ru_RU');

call SETUSSSMSTEMPLATEKEY('rp.apiType.67.spss.success.cm2', '{.case{.compare {CUR}}{.when R}{.then Вы можете продолжать общение! Доверительный платеж {PRPVALR} руб. уже на Вашем балансе. Сумма платежа {PRPVALR} руб. и плата за услугу {FEEVALR} руб. спишутся при пополнении счета или автоматически через {PRPDAYS} дн. Общая сумма к оплате составит {TTLSUMR} руб. за {TTLCOSTR} руб.}{.else Вы можете продолжать общение! Доверительный платеж {PRPVAL}$. уже на Вашем балансе. Сумма платежа {PRPVAL} $. Сумма платежа и плата за услугу {FEEVAL} $ спишутся при пополнении счета или автоматически через {PRPDAYS} дн. Общая сумма к оплате составит {TTLSUM}$ за {TTLCOST}$.}} Вы можете пополнить баланс быстро и без комиссии через приложение "Мой Билайн" www.beeline.ru/dl', 'ru_RU');

call SETUSSSMSTEMPLATEKEY('rp.apiType.77.spss.success.cm2', 'Автодоверительный платёж: доступная сумма - {.case {.compare {CUR}} {.when R} {.then {PRPVALR} руб.}{.else {PRPVALR}$.}} Инфо: тел. 064012', 'ru_RU');
call SETUSSSMSTEMPLATEKEY('rp.apiType.77.spss.success', 'Автодоверительный платёж: доступная сумма - {.case {.compare {CUR}} {.when R} {.then {PRPVALR} руб.}{.else {PRPVALR}$.}} Инфо: тел. 064012 (только в России)', 'ru_RU');

call SETUSSSMSTEMPLATEKEY('rp.apiType.connect.tp.success', 'Вы можете продолжать общение! Доверительный платеж уже на Вашем балансе. Сумма платежа {PRPVAL}{.case{.compare {CUR}}{.when R}{.then руб}{.else $}}. Сумма платежа и плата за услугу {FEEVAL} спишутся при пополнении счета или автоматически через {PRPDAYS} дн {OUTDATE}. Вы можете пополнить баланс быстро и без комиссии через приложение "Мой Билайн" www.beeline.ru/dl', 'ru_RU');
call SETUSSSMSTEMPLATEKEY('rp.apiType.connect.tp.success.free', 'Вам начислен Доверительный платеж на сумму {PRPVAL}{.case{.compare{CUR}}{.when R}{.then руб}{.else $}}. Услуга бесплатная. Сумма платежа спишется при пополнении счета или автоматически через {PRPDAYS} дн. {OUTDATE}. Инфо 064012', 'ru_RU');

insert into BNUMBER_SETTINGS(BNUMBER,PARAM,PARAM_TYPE,PARAM_VALUE  ) values ('141*7', '*', 'oldLogicTrustedPayment  ', 'VIP');
commit;